version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__Default=Host=db;Database=TicketHub;Username=ticketadmin;Password=ticketpassword
    depends_on:
      - db
      
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ticketadmin
      POSTGRES_PASSWORD: ticketpassword
      POSTGRES_DB: TicketHub
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
        
volumes:
  db_data: